apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2-dev
spec:
  template:
    spec:
      containers:
      - name: hello-v2
        env:
        - name: ENVIRONMENT
          value: "dev"