replicaCount: 3

metadata:
  name: hello-v2

matchLabels:
  role: hello-v2

image:
  name: hello-v2
  repository: gcr.io/google-samples/hello-app
  tag: "2.0"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "200m"
  limits:
    memory: "128Mi"
    cpu: "500m"