replicaCount: 3

metadata:
  name: hello-v2

matchLabels:
  role: hello-v2

image:
  name: hello-v2
  repository: gcr.io/google-samples/hello-app
  tag: "2.0"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080