---
# Source: backend2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: hello-v2
---
# Source: backend2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hello-v2
  template:
    metadata:
      labels:
        role: hello-v2
    spec:
      containers:
      - name: hello-v2
        image: "gcr.io/google-samples/hello-app:2.0"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
# Source: backend2/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "backend2-test-connection"
  labels:
    helm.sh/chart: backend2-0.1.0
    app.kubernetes.io/name: backend2
    app.kubernetes.io/instance: backend2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['backend2:8080']
  restartPolicy: Never
