apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1-dev
spec:
  template:
    spec:
      containers:
      - name: hello-v1
        env:
        - name: ENVIRONMENT
          value: "dev"